Sample App Update fix.
moengage/Capacitor-Sample pull request #1
Opened 2023-12-13 09:32 UTC by uday-engg-sdk

https://moengagetrial.atlassian.net/browse/MOEN-28657

Sample Update Fix.

2023-12-14 08:47 UTC, RakshithaAcharya requested changes

2023-12-14 08:47 UTC, RakshithaAcharya commented on Angular/ios/App/App/AppDelegate.swift
> +        let sdkConfig = MoEngageSDKConfig(withAppID:"DAO6UGZ73D9RTK8B5W96TPYN")
@uday-engg-sdk use the new initialiser and   not the deprecated one

2023-12-14 08:47 UTC, RakshithaAcharya commented on Angular/src/app/home/home.page.ts
> +  appId: string = "DAO6UGZ73D9RTK8B5W96TPYN";
@uday-engg-sdk  remove app id

2023-12-14 08:48 UTC, RakshithaAcharya requested changes

2023-12-14 08:48 UTC, RakshithaAcharya commented on Angular/ios/App/App/AppDelegate.swift
> +            UNUserNotificationCenter.current().delegate = self
@uday-engg-sdk  remove this check and set target of the application to 11 and above

2023-12-14 08:48 UTC, RakshithaAcharya commented on Angular/ios/App/App/AppDelegate.swift
> +        sdkConfig.moeDataCenter = .data_center_01
@uday-engg-sdk  replace "" with "YOUR APP ID"

2023-12-14 11:46 UTC, uday-engg-sdk commented on Angular/ios/App/App/AppDelegate.swift
> +        let sdkConfig = MoEngageSDKConfig(withAppID:"DAO6UGZ73D9RTK8B5W96TPYN")
Addressed.

2023-12-14 11:46 UTC, uday-engg-sdk commented on Angular/src/app/home/home.page.ts
> +  appId: string = "DAO6UGZ73D9RTK8B5W96TPYN";
Addressed.

2023-12-14 11:49 UTC, uday-engg-sdk commented on Angular/ios/App/App/AppDelegate.swift
> +        sdkConfig.moeDataCenter = .data_center_01
Addressed.

2023-12-14 12:04 UTC, uday-engg-sdk commented on Angular/ios/App/App/AppDelegate.swift
> +            UNUserNotificationCenter.current().delegate = self
@RakshithaAcharya, since the "CapacitorMoengageCore" framework has minimum deployment iOS version: 13.0 set in ".podspec", file of "capacitor-moengage-core" we cannot set the deployment iOS version to 11.0 and above as it gives compiler error. Correct me if I am wrong.

2023-12-14 12:23 UTC, RakshithaAcharya commented on Angular/ios/App/App/AppDelegate.swift
> +            UNUserNotificationCenter.current().delegate = self
@uday-engg-sdk Then why is that if condition needed?

2023-12-18 04:58 UTC, RakshithaAcharya approved these changes

2023-12-18 12:30 UTC, merged